#!/bin/bash
# Lokale Laufreihe Spur cpu (DIM-BEUTEL): je Zeile ein ssh-Aufruf von kleintest.sh im vorgeschriebenen Format.
D=/home/fmh/fmhc-physics/coordination/runden-v3/RUNDE-16/dim-beutel
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu db-kub64-auf code/dimbeutel.py ast --graph kubisch --size 64 --tag kub64-auf --out aus/haupt --kstart 40 --kende 77 --richtung 1' > $D/aus/logs/kub64-auf.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu db-ket4096-auf code/dimbeutel.py ast --graph kette --size 4096 --tag ket4096-auf --out aus/haupt --kstart 40 --kende 79 --richtung 1' > $D/aus/logs/ket4096-auf.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu db-ket4096-ab code/dimbeutel.py ast --graph kette --size 4096 --tag ket4096-ab --out aus/haupt --kstart 40 --kende 0 --richtung -1' > $D/aus/logs/ket4096-ab.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu db-sie10s1-ab code/dimbeutel.py ast --graph sierpinski --size 10 --start s1 --tag sie10s1-ab --out aus/haupt --kstart 40 --kende 0 --richtung -1' > $D/aus/logs/sie10s1-ab.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu db-sie10s2-auf code/dimbeutel.py ast --graph sierpinski --size 10 --start s2 --tag sie10s2-auf --out aus/kontrolle --kstart 40 --kende 87 --richtung 1' > $D/aus/logs/sie10s2-auf.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu db-kub48-auf code/dimbeutel.py ast --graph kubisch --size 48 --tag kub48-auf --out aus/kontrolle --kstart 40 --kende 70 --richtung 1' > $D/aus/logs/kub48-auf.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu db-frisch-kub64 code/dimbeutel.py frisch --graph kubisch --size 64 --tag kub64 --out aus/frisch --klist 30,50,70 --formen A,B' > $D/aus/logs/frisch-kub64.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu db-frisch-ket code/dimbeutel.py frisch --graph kette --size 4096 --tag ket4096 --out aus/frisch --klist 30,50,70 --formen A,B' > $D/aus/logs/frisch-ket4096.log 2>&1
date --iso-8601=seconds > $D/aus/logs/spur-cpu.fertig
