#!/bin/bash
# Lokale Laufreihe Spur cpu2 (DIM-BEUTEL): je Zeile ein ssh-Aufruf von kleintest.sh im vorgeschriebenen Format.
D=/home/fmh/fmhc-physics/coordination/runden-v3/RUNDE-16/dim-beutel
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu2 db-sie10s1-auf code/dimbeutel.py ast --graph sierpinski --size 10 --start s1 --tag sie10s1-auf --out aus/haupt --kstart 40 --kende 87 --richtung 1' > $D/aus/logs/sie10s1-auf.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu2 db-qu256-auf code/dimbeutel.py ast --graph quadrat --size 256 --tag qu256-auf --out aus/haupt --kstart 40 --kende 79 --richtung 1' > $D/aus/logs/qu256-auf.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu2 db-kub64-ab code/dimbeutel.py ast --graph kubisch --size 64 --tag kub64-ab --out aus/haupt --kstart 40 --kende 0 --richtung -1' > $D/aus/logs/kub64-ab.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu2 db-qu256-ab code/dimbeutel.py ast --graph quadrat --size 256 --tag qu256-ab --out aus/haupt --kstart 40 --kende 0 --richtung -1' > $D/aus/logs/qu256-ab.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu2 db-qu192-auf code/dimbeutel.py ast --graph quadrat --size 192 --tag qu192-auf --out aus/kontrolle --kstart 40 --kende 73 --richtung 1' > $D/aus/logs/qu192-auf.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu2 db-sie9s1-auf code/dimbeutel.py ast --graph sierpinski --size 9 --start s1 --tag sie9s1-auf --out aus/kontrolle --kstart 40 --kende 75 --richtung 1' > $D/aus/logs/sie9s1-auf.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu2 db-ds code/dimbeutel.py ds --out aus/ds --ds-g 7 --walk-g 10 --walk-starts s1,s2 --walk-tmax 15625' > $D/aus/logs/ds.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu2 db-frisch-sie10 code/dimbeutel.py frisch --graph sierpinski --size 10 --start s1 --tag sie10s1 --out aus/frisch --klist 30,50,70,80 --formen A,B' > $D/aus/logs/frisch-sie10s1.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu2 db-frisch-qu256 code/dimbeutel.py frisch --graph quadrat --size 256 --tag qu256 --out aus/frisch --klist 30,50,70 --formen A,B' > $D/aus/logs/frisch-qu256.log 2>&1
ssh fmh@192.168.178.69 'cd /home/fmh/fmhc-physics-remote/runde16-dim-beutel && bash /home/fmh/fmhc-physics-remote/kleintests/kleintest.sh cpu2 db-ket8192-auf code/dimbeutel.py ast --graph kette --size 8192 --tag ket8192-auf --out aus/kontrolle --kstart 40 --kende 79 --richtung 1' > $D/aus/logs/ket8192-auf.log 2>&1
date --iso-8601=seconds > $D/aus/logs/spur-cpu2.fertig
